/* C ABI of the pgvfs Rust staticlib (src/lib.rs); generated by cbindgen, do not edit. */

#ifndef PGVFS_H
#define PGVFS_H

#include <stddef.h>
#include <stdint.h>

typedef struct PgvfsConn PgvfsConn;

typedef struct PgvfsWriter PgvfsWriter;

typedef struct {
    int64_t file_id;
    int64_t size;
    /*
     Microseconds since the Unix epoch.
     */
    int64_t created_us;
} PgvfsFile;

typedef void (*pgvfs_list_cb)(void *ctx, const char *path, size_t len);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/*
 Connect and verify the layout (read access suffices), sized for a DuckDB
 with `threads` threads (<= 0: one per core). NULL + `*err` on failure.
 */
PgvfsConn *pgvfs_connect(const char *url, int64_t threads, char **err);

void pgvfs_disconnect(PgvfsConn *c);

void pgvfs_free_str(char *s);

/*
 0 found (fills `out`), 1 not found, -1 error.
 */
int pgvfs_open(const PgvfsConn *c,
               const char *volume,
               const char *path,
               PgvfsFile *out,
               char **err);

/*
 Fill exactly `len` bytes from `pos`; the range must lie inside the file.
 0 ok, -1 error.
 */
int pgvfs_read(const PgvfsConn *c,
               const PgvfsFile *file,
               uint8_t *buf,
               int64_t len,
               int64_t pos,
               char **err);

/*
 Process-wide counters as JSON (free with `pgvfs_free_str`). Cumulative:
 callers diff two samples.
 */
char *pgvfs_stats(void);

/*
 Call `cb` for each path under `prefix`, in byte order, as the rows stream
 in (`limit` paths at most; a negative limit means all). 0 ok, -1 error.
 */
int pgvfs_list(const PgvfsConn *c,
               const char *volume,
               const char *prefix,
               int64_t limit,
               pgvfs_list_cb cb,
               void *ctx,
               char **err);

/*
 0 removed, 1 not found, -1 error.
 */
int pgvfs_remove(const PgvfsConn *c, const char *volume, const char *path, char **err);

/*
 Remove every file under `prefix` ("" for the whole volume). Returns how
 many, or -1.
 */
int64_t pgvfs_remove_prefix(const PgvfsConn *c, const char *volume, const char *prefix, char **err);

/*
 Rename within a volume, replacing the target. 0 ok, -1 error.
 */
int pgvfs_rename(const PgvfsConn *c,
                 const char *volume,
                 const char *from,
                 const char *to,
                 char **err);

/*
 Start writing a new file at `path`. It is published (replacing any file
 there) only by `pgvfs_writer_publish`; `pgvfs_writer_abort` discards it.
 */
PgvfsWriter *pgvfs_writer_open(const PgvfsConn *c,
                               const char *volume,
                               const char *path,
                               char **err);

/*
 Append `len` bytes. 0 ok, -1 error (the file is then unpublishable).
 */
int pgvfs_writer_write(PgvfsWriter *w, const uint8_t *buf, int64_t len, char **err);

/*
 Publish and free the writer. 0 ok, -1 error (nothing published).
 */
int pgvfs_writer_publish(PgvfsWriter *w, char **err);

/*
 Discard and free the writer; nothing is published.
 */
void pgvfs_writer_abort(PgvfsWriter *w);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* PGVFS_H */
