/* C ABI of the tantivy Rust crate (tantivy/src/lib.rs); generated by cbindgen, do not edit. */

#ifndef TANTIVY_H
#define TANTIVY_H

#include <stddef.h>
#include <stdint.h>

/*
 A split being built, in a local temporary directory (removed on drop).
 */
typedef struct TantivyBuild TantivyBuild;

/*
 A split open for search.
 */
typedef struct TantivySplit TantivySplit;

typedef int (*tantivy_write_cb)(void *ctx, const uint8_t *buf, uint64_t len, char *msg, size_t cap);

typedef int (*tantivy_read_cb)(void *ctx,
                               uint8_t *buf,
                               uint64_t len,
                               uint64_t offset,
                               char *msg,
                               size_t cap);

typedef void (*tantivy_hit_cb)(void *ctx,
                               size_t split,
                               double score,
                               const char *doc,
                               size_t len,
                               const char *highlight,
                               size_t highlight_len);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

void tantivy_free_str(char *s);

/*
 Start a split: `schema` is a tantivy schema as JSON, `options` (may be
 NULL) build options as JSON. `threads` indexing threads (at least 1) share
 the build's memory budget; `live` builds of the same query are already open,
 and `max_memory` is DuckDB's memory limit in bytes (0: none). NULL + `*err`
 on failure.
 */
TantivyBuild *tantivy_build_open(const char *schema,
                                 const char *options,
                                 size_t threads,
                                 size_t live,
                                 uint64_t max_memory,
                                 char **err);

/*
 Add one document (a JSON object), from any thread. 0 ok, -1 error.
 */
int tantivy_build_add(const TantivyBuild *b, const char *doc, size_t len, char **err);

/*
 Commit, write the split to `cb`, and free the build. Returns the documents
 indexed, or -1.
 */
int64_t tantivy_build_finish(TantivyBuild *b, tantivy_write_cb cb, void *ctx, char **err);

/*
 Discard and free the build.
 */
void tantivy_build_abort(TantivyBuild *b);

/*
 Open the split of `size` bytes that `cb` reads, from any thread, with
 `ctx`. NULL + `*err` on failure.
 */
TantivySplit *tantivy_split_open(uint64_t size, tantivy_read_cb cb, void *ctx, char **err);

void tantivy_split_close(TantivySplit *s);

/*
 Search `n` splits with a query (tantivy's syntax, or OpenSearch query DSL
 as JSON); `options` (may be NULL) is search options as JSON. Calls `cb` per
 hit, best first: its split's position, score (NaN when the hits are ordered
 by a field), doc as a JSON object and, if asked for, its snippets as a JSON
 object (NULL otherwise). 0 ok, -1 error.
 */
int tantivy_search(const TantivySplit *const *s,
                   size_t n,
                   const char *query,
                   const char *options,
                   int exclude_kind,
                   const void *exclude_data,
                   size_t exclude_len,
                   size_t threads,
                   tantivy_hit_cb cb,
                   void *ctx,
                   char **err);

/*
 The number of matches over `n` splits, or -1.
 */
int64_t tantivy_count(const TantivySplit *const *s,
                      size_t n,
                      const char *query,
                      const char *options,
                      int exclude_kind,
                      const void *exclude_data,
                      size_t exclude_len,
                      size_t threads,
                      char **err);

/*
 Tantivy aggregations (`aggs`, Elasticsearch's JSON) over the matches in
 `n` splits, merged; the result in `*out` (free with `tantivy_free_str`).
 0 ok, -1 error.
 */
int tantivy_aggregate(const TantivySplit *const *s,
                      size_t n,
                      const char *query,
                      const char *aggs,
                      const char *options,
                      int exclude_kind,
                      const void *exclude_data,
                      size_t exclude_len,
                      size_t threads,
                      char **out,
                      char **err);

/*
 Merge `n` splits into one without the excluded documents, written to
 `cb`. Returns the documents kept, or -1.
 */
int64_t tantivy_merge(const TantivySplit *const *s,
                      size_t n,
                      const char *options,
                      int exclude_kind,
                      const void *exclude_data,
                      size_t exclude_len,
                      tantivy_write_cb cb,
                      void *ctx,
                      char **err);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* TANTIVY_H */
